source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

xcodeproj 'SlidingTabBar.xcodeproj'

target 'SlidingTabBar_Example', :exclusive => true do
  pod 'SlidingTabBar', :path => '../'
end

target 'SlidingTabBar_Tests', :exclusive => true do
  pod 'SlidingTabBar', :path => '../'

  
end
